package io.securecodebox.constants;

public enum ZapFields {

    ZAP_TARGET_NAME,
    ZAP_TARGET_URL,
    ZAP_AUTHENTICATION,
    ZAP_RESULT_APPROVED,
    ZAP_SPIDER_RUN_ID,
    ZAP_SPIDER_TARGET_URL,
    ZAP_SPIDER_INCLUDE_REGEX,
    ZAP_SPIDER_EXCLUDE_REGEX,
    ZAP_SPIDER_EXLUDE_DUPLICATES,
    ZAP_SPIDER_MAX_DEPTH,
    ZAP_SCANNER_RUN_ID,
    ZAP_SCANNER_TARGET_URL,
    ZAP_SCANNER_INCLUDE_REGEX,
    ZAP_SCANNER_EXLUDE_REGEX,
    ZAP_REPORTING_CONFIGURATION_TYPE,
    ZAP_REPORTING_TYPES,
    ZAP_REPORTING_SERVICE_ID,
    ZAP_REPORTING_SERVICE_RUN_ID,
    ZAP_REPORTING_SERVICE_HOST,
    ZAP_REPORTING_DASHBOARD_URL,
    ZAP_REPORTING_DASHBOARD_BY_TIME_URL,
    ZAP_REPORTING_FALSE_POSITIVES
}
