package io.securecodebox.scanprocess.zap.constants;

public enum ZapFields {

    ZAP_TARGET_NAME,
    ZAP_TARGET_URL,
    ZAP_AUTHENTICATION,
    ZAP_SPIDER_RUN_ID,
    ZAP_SPIDER_TARGET_URL,
    ZAP_SPIDER_INCLUDE_REGEX,
    ZAP_SPIDER_EXCLUDE_REGEX,
    ZAP_SPIDER_EXCLUDE_DUPLICATES,
    ZAP_SPIDER_MAX_DEPTH,
    ZAP_SCANNER_RUN_ID,
    ZAP_SCANNER_TARGET_URL,
    ZAP_SCANNER_INCLUDE_REGEX,
    ZAP_SCANNER_EXCLUDE_REGEX,
    ZAP_LOGIN_SITE,
    ZAP_LOGIN_USER,
    ZAP_USERNAME_FIELD_ID,
    ZAP_LOGIN_PW,
    ZAP_PW_FIELD_ID,
    ZAP_LOGGED_IN_INDICATOR,
    ZAP_CSRF_TOKEN_ID
}
